import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        pixel: ['"VT323"', 'monospace'],
        body: ['"Orbitron"', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        void: "hsl(var(--bg-void))",
        base: "hsl(var(--bg-base))",
        elevated: "hsl(var(--bg-elevated))",
        panel: "hsl(var(--bg-panel))",
        "bg-input": "hsl(var(--bg-input))",
        "bg-hover": "hsl(var(--bg-hover))",
        craft: {
          green: "hsl(var(--craft-green))",
          blue: "hsl(var(--craft-blue))",
          purple: "hsl(var(--craft-purple))",
          yellow: "hsl(var(--craft-yellow))",
          red: "hsl(var(--craft-red))",
          orange: "hsl(var(--craft-orange))",
        },
        "green-dim": "hsl(var(--craft-green-dim))",
        "blue-dim": "hsl(var(--craft-blue-dim))",
        "purple-dim": "hsl(var(--craft-purple-dim))",
        "yellow-dim": "hsl(var(--craft-yellow-dim))",
        "red-dim": "hsl(var(--craft-red-dim))",
        "orange-dim": "hsl(var(--craft-orange-dim))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      boxShadow: {
        'glow-green': '0 0 20px rgba(57,211,83,0.3)',
        'glow-blue': '0 0 20px rgba(88,166,255,0.3)',
        'glow-red': '0 0 20px rgba(248,81,73,0.3)',
        'glow-purple': '0 0 20px rgba(188,140,255,0.3)',
        'card': '0 1px 3px rgba(0,0,0,0.5), 0 0 0 1px rgba(48,54,61,0.5)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideRight: { '0%': { opacity: '0', transform: 'translateX(40px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        float: { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
        pixelBlink: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        progressFill: { '0%': { width: '0%' }, '100%': { width: 'var(--target-width)' } },
        celebration: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.05)' }, '100%': { transform: 'scale(1)' } },
        confettiFall: { '0%': { transform: 'translateY(-20px) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(110vh) rotate(720deg)', opacity: '0' } },
        shake: { '0%,100%': { transform: 'translateX(0)' }, '20%': { transform: 'translateX(-6px)' }, '40%': { transform: 'translateX(6px)' }, '60%': { transform: 'translateX(-4px)' }, '80%': { transform: 'translateX(4px)' } },
        countUp: { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        'slide-up': 'slideUp 0.4s ease-out forwards',
        'slide-right': 'slideRight 0.3s ease-out forwards',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'float': 'float 4s ease-in-out infinite',
        'pixel-blink': 'pixelBlink 1s step-end infinite',
        'progress-fill': 'progressFill 0.8s ease-out forwards',
        'count-up': 'countUp 1s ease-out forwards',
        'celebration': 'celebration 0.6s ease-out forwards',
        'confetti-fall': 'confettiFall var(--duration) linear var(--delay) forwards',
        'shake': 'shake 0.4s ease-in-out',
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
